Repository spartaSpringTeamA6/dev-quiz-backend, pull requests merged in 2024-01, with the labels that each got.

#12 ✨feat: user entity 수정, userCustomException 생성 (#4)
  src/main/java/com/sparta/devquiz/domain/user/entity/User.java
  src/main/java/com/sparta/devquiz/domain/user/exception/UserCustomException.java
  src/main/java/com/sparta/devquiz/domain/user/exception/UserExceptionCode.java
  src/main/java/com/sparta/devquiz/domain/user/repository/UserRepository.java
  src/main/java/com/sparta/devquiz/domain/user/response/UserResponseCode.java
  src/main/java/com/sparta/devquiz/domain/user/service/UserService.java
Labels: feat, fix

#13 #7 ✨feat: coin rename, 조회기능 구현
  src/main/java/com/sparta/devquiz/domain/coin/controller/CoinController.java
  src/main/java/com/sparta/devquiz/domain/coin/dto/request/SaveCoinRequest.java
  src/main/java/com/sparta/devquiz/domain/coin/dto/request/UseCoinRequest.java
  src/main/java/com/sparta/devquiz/domain/coin/dto/response/GetCoinInfoResponse.java
  src/main/java/com/sparta/devquiz/domain/coin/dto/response/SaveCoinResponse.java
  src/main/java/com/sparta/devquiz/domain/coin/dto/response/UseCoinResponse.java
  src/main/java/com/sparta/devquiz/domain/coin/entity/Coin.java
  src/main/java/com/sparta/devquiz/domain/coin/enums/CoinContent.java
  src/main/java/com/sparta/devquiz/domain/coin/enums/CoinStatus.java
  src/main/java/com/sparta/devquiz/domain/coin/exception/CoinCustomException.java
  src/main/java/com/sparta/devquiz/domain/coin/exception/CoinExceptionCode.java
  src/main/java/com/sparta/devquiz/domain/coin/repository/CoinRepository.java
  src/main/java/com/sparta/devquiz/domain/coin/response/CoinResponseCode.java
  src/main/java/com/sparta/devquiz/domain/coin/service/CoinService.java
  src/main/java/com/sparta/devquiz/domain/point/enums/PointContent.java
  src/main/java/com/sparta/devquiz/domain/point/response/PointResponseCode.java
  src/main/java/com/sparta/devquiz/domain/user/entity/User.java
Labels: feat

#18 :sparkles: feat(Global): response 관련 변경점 (#16)
  src/main/java/com/sparta/devquiz/global/response/ResponseCode.java
Labels: feat

#23 DomainInfoResponse, DomainInfoDetailResponse 예시
  src/main/java/com/sparta/devquiz/domain/team/dto/response/TeamInfoDetailResponse.java
  src/main/java/com/sparta/devquiz/domain/team/dto/response/TeamInfoResponse.java
  src/main/java/com/sparta/devquiz/domain/user/dto/response/UserInfoResponse.java
Labels: feat

#25 :sparkles: JwtUtil 기능, Security 설정, Oauth2 로그인 기능 구현 (#24)
  src/main/java/com/sparta/devquiz/DevQuizApplication.java
  src/main/java/com/sparta/devquiz/global/jwt/JwtAuthorizationFilter.java
  src/main/java/com/sparta/devquiz/global/jwt/JwtExceptionHandlerFilter.java
  src/main/java/com/sparta/devquiz/global/jwt/JwtUtil.java
  src/main/java/com/sparta/devquiz/global/jwt/exception/JwtCustomException.java
  src/main/java/com/sparta/devquiz/global/jwt/exception/JwtExceptionCode.java
  src/main/java/com/sparta/devquiz/global/oauth/OAuth2Attributes.java
  src/main/java/com/sparta/devquiz/global/oauth/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/sparta/devquiz/global/oauth/service/CustomOAuth2UserService.java
  src/main/java/com/sparta/devquiz/global/oauth/userinfo/GithubUserInfo.java
  src/main/java/com/sparta/devquiz/global/oauth/userinfo/GoogleUserInfo.java
  src/main/java/com/sparta/devquiz/global/oauth/userinfo/OAuth2UserInfo.java
  src/main/java/com/sparta/devquiz/global/security/UserDetailsImpl.java
  src/main/java/com/sparta/devquiz/global/security/UserDetailsServiceImpl.java
  src/main/java/com/sparta/devquiz/global/security/WebSecurityConfig.java
  src/main/resources/application.yml
Labels: feat

#20 coin 기능 구현
  build.gradle
  src/main/java/com/sparta/devquiz/domain/coin/controller/CoinController.java
  src/main/java/com/sparta/devquiz/domain/coin/dto/request/SaveCoinRequest.java
  src/main/java/com/sparta/devquiz/domain/coin/dto/request/UseCoinRequest.java
  src/main/java/com/sparta/devquiz/domain/coin/dto/response/GetCoinInfoResponse.java
  src/main/java/com/sparta/devquiz/domain/coin/dto/response/UseCoinResponse.java
  src/main/java/com/sparta/devquiz/domain/coin/entity/Coin.java
  src/main/java/com/sparta/devquiz/domain/coin/enums/CoinContent.java
  src/main/java/com/sparta/devquiz/domain/coin/enums/CoinStatus.java
  src/main/java/com/sparta/devquiz/domain/coin/repository/CoinRepository.java
  src/main/java/com/sparta/devquiz/domain/coin/response/CoinResponseCode.java
  src/main/java/com/sparta/devquiz/domain/coin/service/CoinService.java
  src/test/java/com/sparta/devquiz/domain/coin/service/CoinServiceTest.java
Labels: feat, test

#31 Refactor Team API
  src/main/java/com/sparta/devquiz/domain/team/controller/TeamController.java
  src/main/java/com/sparta/devquiz/domain/team/entity/TeamUser.java
  src/main/java/com/sparta/devquiz/domain/team/service/TeamService.java
Labels: refactor

#33 Refactor Team API
  build.gradle
  src/main/java/com/sparta/devquiz/domain/team/controller/TeamController.java
  src/main/java/com/sparta/devquiz/domain/team/dto/response/TeamCreateResponse.java
  src/main/java/com/sparta/devquiz/domain/team/dto/response/TeamGetResponse.java
  src/main/java/com/sparta/devquiz/domain/team/dto/response/TeamGetUserRankingResponse.java
  src/main/java/com/sparta/devquiz/domain/team/repository/TeamUserRepository.java
  src/main/java/com/sparta/devquiz/domain/team/service/TeamService.java
  src/main/java/com/sparta/devquiz/domain/team/service/TeamUserService.java
  src/main/java/com/sparta/devquiz/domain/user/dto/response/UserRankingResponse.java
Labels: refactor

#34 Feat/point
  src/main/java/com/sparta/devquiz/domain/coin/exception/CoinExceptionCode.java
  src/test/java/com/sparta/devquiz/domain/coin/service/CoinServiceTest.java
Labels: chore, fix

#39 📌chore: url 수정 (#7)
  src/main/java/com/sparta/devquiz/domain/coin/controller/CoinController.java
Labels: chore

#40 🚚rename: dto명 코드 컨벤션 적용 (#7)
  src/main/java/com/sparta/devquiz/domain/coin/controller/CoinController.java
  src/main/java/com/sparta/devquiz/domain/coin/dto/request/CoinSaveRequest.java
  src/main/java/com/sparta/devquiz/domain/coin/dto/request/CoinUseRequest.java
  src/main/java/com/sparta/devquiz/domain/coin/dto/response/CoinGetInfoResponse.java
  src/main/java/com/sparta/devquiz/domain/coin/dto/response/CoinUseResponse.java
  src/main/java/com/sparta/devquiz/domain/coin/service/CoinService.java
  src/test/java/com/sparta/devquiz/domain/coin/service/CoinServiceTest.java
Labels: rename

#41 ♻️refactor: url 매핑변경 (#7)
  src/main/java/com/sparta/devquiz/domain/coin/controller/CoinController.java
  src/main/java/com/sparta/devquiz/domain/coin/dto/response/CoinGetInfoResponse.java
Labels: refactor

#42 ♻️refactor: 트랜잭션 변경 (#7)
  src/main/java/com/sparta/devquiz/domain/coin/service/CoinService.java
Labels: refactor

#43 ♻️ refactor(User): UserService 세분화 (#4)
  src/main/java/com/sparta/devquiz/domain/mypage/service/UserTeamUserService.java
  src/main/java/com/sparta/devquiz/domain/user/controller/UserController.java
  src/main/java/com/sparta/devquiz/domain/user/dto/request/UserUpdateRequest.java
  src/main/java/com/sparta/devquiz/domain/user/enums/UserRole.java
  src/main/java/com/sparta/devquiz/domain/user/service/UserService.java
Labels: feat, refactor, fix

#44 ♻️ refactor(Auth): OAuthFilter 세션 방식이 아닌 Cookie 방식으로 변경 (#24)
  src/main/java/com/sparta/devquiz/domain/user/controller/AuthController.java
  src/main/java/com/sparta/devquiz/domain/user/dto/response/UserInvitationsResponse.java
  src/main/java/com/sparta/devquiz/domain/user/response/UserResponseCode.java
  src/main/java/com/sparta/devquiz/domain/user/service/AuthService.java
  src/main/java/com/sparta/devquiz/global/jwt/dto/TokenSet.java
  src/main/java/com/sparta/devquiz/global/jwt/exception/JwtExceptionCode.java
  src/main/java/com/sparta/devquiz/global/jwt/filter/JwtAuthorizationFilter.java
  src/main/java/com/sparta/devquiz/global/jwt/filter/JwtExceptionHandlerFilter.java
  src/main/java/com/sparta/devquiz/global/jwt/service/JwtService.java
  src/main/java/com/sparta/devquiz/global/oauth/CookieUtil.java
  src/main/java/com/sparta/devquiz/global/oauth/OAuth2Attributes.java
  src/main/java/com/sparta/devquiz/global/oauth/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/sparta/devquiz/global/oauth/repository/CookieOAuth2RequestRepository.java
  src/main/java/com/sparta/devquiz/global/redis/RedisService.java
  src/main/java/com/sparta/devquiz/global/security/WebSecurityConfig.java
Labels: feat, refactor

#35 Feat/board
  src/main/java/com/sparta/devquiz/domain/board/controller/BoardController.java
  src/main/java/com/sparta/devquiz/domain/board/dto/request/BoardCreateRequest.java
  src/main/java/com/sparta/devquiz/domain/board/dto/request/BoardUpdateRequest.java
  src/main/java/com/sparta/devquiz/domain/board/dto/response/BoardCreateResponse.java
  src/main/java/com/sparta/devquiz/domain/board/dto/response/BoardDetailsResponse.java
  src/main/java/com/sparta/devquiz/domain/board/entity/Board.java
  src/main/java/com/sparta/devquiz/domain/board/exception/BoardCustomException.java
  src/main/java/com/sparta/devquiz/domain/board/exception/BoardExceptionCode.java
  src/main/java/com/sparta/devquiz/domain/board/repository/BoardRepository.java
  src/main/java/com/sparta/devquiz/domain/board/response/BoardResponseCode.java
  src/main/java/com/sparta/devquiz/domain/board/service/BoardService.java
  src/main/java/com/sparta/devquiz/domain/comment/controller/CommentController.java
  src/main/java/com/sparta/devquiz/domain/comment/dto/request/CommentCreateRequest.java
  src/main/java/com/sparta/devquiz/domain/comment/dto/request/CommentUpdateRequest.java
  src/main/java/com/sparta/devquiz/domain/comment/dto/response/CommentCreateResponse.java
  src/main/java/com/sparta/devquiz/domain/comment/dto/response/CommentDetailsResponse.java
  src/main/java/com/sparta/devquiz/domain/comment/entity/Comment.java
  src/main/java/com/sparta/devquiz/domain/comment/entity/CommentLikeId.java
  src/main/java/com/sparta/devquiz/domain/comment/exception/CommentCustomException.java
  src/main/java/com/sparta/devquiz/domain/comment/exception/CommentExceptionCode.java
  src/main/java/com/sparta/devquiz/domain/comment/repository/CommentLikeRepository.java
  src/main/java/com/sparta/devquiz/domain/comment/repository/CommentRepository.java
  src/main/java/com/sparta/devquiz/domain/comment/response/CommentResponseCode.java
  src/main/java/com/sparta/devquiz/domain/comment/service/CommentService.java
Labels: feat

#46 Feat/quiz
  src/main/java/com/sparta/devquiz/domain/board/service/BoardService.java
  src/main/java/com/sparta/devquiz/domain/quiz/controller/QuizController.java
  src/main/java/com/sparta/devquiz/domain/quiz/dto/request/QuizAnswerSubmitRequest.java
  src/main/java/com/sparta/devquiz/domain/quiz/dto/request/QuizCreateRequest.java
  src/main/java/com/sparta/devquiz/domain/quiz/dto/request/QuizDeleteRequest.java
  src/main/java/com/sparta/devquiz/domain/quiz/dto/request/QuizDetailRequest.java
  src/main/java/com/sparta/devquiz/domain/quiz/dto/request/QuizRandomRequest.java
  src/main/java/com/sparta/devquiz/domain/quiz/dto/request/QuizUpdateRequest.java
  src/main/java/com/sparta/devquiz/domain/quiz/dto/response/QuizAnswerSubmitResponse.java
  src/main/java/com/sparta/devquiz/domain/quiz/dto/response/QuizCorrectUserResponse.java
  src/main/java/com/sparta/devquiz/domain/quiz/dto/response/QuizCreateResponse.java
  src/main/java/com/sparta/devquiz/domain/quiz/dto/response/QuizDeleteResponse.java
  src/main/java/com/sparta/devquiz/domain/quiz/dto/response/QuizDetailResponse.java
  src/main/java/com/sparta/devquiz/domain/quiz/dto/response/QuizFailUserResponse.java
  src/main/java/com/sparta/devquiz/domain/quiz/dto/response/QuizInfoResponse.java
  src/main/java/com/sparta/devquiz/domain/quiz/dto/response/QuizPassUserResponse.java
  src/main/java/com/sparta/devquiz/domain/quiz/dto/response/QuizRandomResponse.java
  src/main/java/com/sparta/devquiz/domain/quiz/dto/response/QuizUpdateResponse.java
  src/main/java/com/sparta/devquiz/domain/quiz/entity/Quiz.java
  src/main/java/com/sparta/devquiz/domain/quiz/entity/UserQuizId.java
  src/main/java/com/sparta/devquiz/domain/quiz/enums/QuizCategory.java
  src/main/java/com/sparta/devquiz/domain/quiz/enums/UserQuizStatus.java
  src/main/java/com/sparta/devquiz/domain/quiz/exception/QuizCustomException.java
  src/main/java/com/sparta/devquiz/domain/quiz/exception/QuizExceptionCode.java
  src/main/java/com/sparta/devquiz/domain/quiz/repository/QuizRepository.java
  src/main/java/com/sparta/devquiz/domain/quiz/repository/QuizUserRepository.java
  src/main/java/com/sparta/devquiz/domain/quiz/response/QuizResponseCode.java
  src/main/java/com/sparta/devquiz/domain/quiz/service/QuizService.java
  src/main/java/com/sparta/devquiz/domain/user/entity/User.java
  src/main/java/com/sparta/devquiz/domain/user/repository/UserRepository.java
  src/main/java/com/sparta/devquiz/global/oauth/OAuth2Attributes.java
Labels: feat

#47 :recycle: refactor: team
  build.gradle
  src/main/java/com/sparta/devquiz/domain/board/service/BoardService.java
  src/main/java/com/sparta/devquiz/domain/mypage/service/UserTeamUserService.java
  src/main/java/com/sparta/devquiz/domain/team/controller/TeamController.java
  src/main/java/com/sparta/devquiz/domain/team/dto/request/TeamCreateRequest.java
  src/main/java/com/sparta/devquiz/domain/team/dto/request/TeamDeleteUserRequest.java
  src/main/java/com/sparta/devquiz/domain/team/dto/request/TeamInviteUserRequest.java
  src/main/java/com/sparta/devquiz/domain/team/dto/request/TeamUpdateAdminRequest.java
  src/main/java/com/sparta/devquiz/domain/team/dto/request/TeamUpdateNameRequest.java
  src/main/java/com/sparta/devquiz/domain/team/dto/request/TeamWithdrawRequest.java
  src/main/java/com/sparta/devquiz/domain/team/dto/response/TeamCreateResponse.java
  src/main/java/com/sparta/devquiz/domain/team/dto/response/TeamGetResponse.java
  src/main/java/com/sparta/devquiz/domain/team/dto/response/TeamGetUserRankingResponse.java
  src/main/java/com/sparta/devquiz/domain/team/dto/response/TeamInfoDetailResponse.java
  src/main/java/com/sparta/devquiz/domain/team/dto/response/TeamInfoResponse.java
  src/main/java/com/sparta/devquiz/domain/team/response/TeamResponseCode.java
  src/main/java/com/sparta/devquiz/domain/team/service/TeamService.java
  src/main/java/com/sparta/devquiz/domain/team/service/TeamUserService.java
Labels: refactor

#50 ♻️ Refactor Quiz
  src/main/java/com/sparta/devquiz/domain/quiz/controller/QuizController.java
  src/main/java/com/sparta/devquiz/domain/quiz/dto/request/QuizDeleteRequest.java
  src/main/java/com/sparta/devquiz/domain/quiz/dto/request/QuizDetailRequest.java
  src/main/java/com/sparta/devquiz/domain/quiz/dto/request/QuizRandomRequest.java
  src/main/java/com/sparta/devquiz/domain/quiz/dto/request/QuizUpdateRequest.java
  src/main/java/com/sparta/devquiz/domain/quiz/dto/response/QuizAnswerSubmitResponse.java
  src/main/java/com/sparta/devquiz/domain/quiz/dto/response/QuizCorrectUserResponse.java
  src/main/java/com/sparta/devquiz/domain/quiz/dto/response/QuizCreateResponse.java
  src/main/java/com/sparta/devquiz/domain/quiz/dto/response/QuizDeleteResponse.java
  src/main/java/com/sparta/devquiz/domain/quiz/dto/response/QuizDetailResponse.java
  src/main/java/com/sparta/devquiz/domain/quiz/dto/response/QuizFailUserResponse.java
  src/main/java/com/sparta/devquiz/domain/quiz/dto/response/QuizGetQuizzesByUserResponse.java
  src/main/java/com/sparta/devquiz/domain/quiz/dto/response/QuizInfoResponse.java
  src/main/java/com/sparta/devquiz/domain/quiz/dto/response/QuizPassUserResponse.java
  src/main/java/com/sparta/devquiz/domain/quiz/dto/response/QuizRandomResponse.java
  src/main/java/com/sparta/devquiz/domain/quiz/dto/response/QuizUpdateResponse.java
  src/main/java/com/sparta/devquiz/domain/quiz/entity/Quiz.java
  src/main/java/com/sparta/devquiz/domain/quiz/enums/UserQuizStatus.java
  src/main/java/com/sparta/devquiz/domain/quiz/repository/QuizUserRepository.java
  src/main/java/com/sparta/devquiz/domain/quiz/repository/QuizUserRepositoryCustom.java
  src/main/java/com/sparta/devquiz/domain/quiz/repository/QuizUserRepositoryCustomImpl.java
  src/main/java/com/sparta/devquiz/domain/quiz/service/QuizService.java
  src/main/java/com/sparta/devquiz/global/jpa/JpaQueryConfig.java
  src/main/java/com/sparta/devquiz/global/security/WebSecurityConfig.java
Labels: refactor

#51 :sparkles: refactor(Quiz): 리팩토링 (#5)
  src/main/java/com/sparta/devquiz/domain/quiz/controller/QuizController.java
  src/main/java/com/sparta/devquiz/domain/quiz/dto/response/QuizCorrectUserResponse.java
  src/main/java/com/sparta/devquiz/domain/quiz/dto/response/QuizDetailInfoResponse.java
  src/main/java/com/sparta/devquiz/domain/quiz/dto/response/QuizDetailResponse.java
  src/main/java/com/sparta/devquiz/domain/quiz/dto/response/QuizGetByUserResponse.java
  src/main/java/com/sparta/devquiz/domain/quiz/dto/response/QuizPassUserResponse.java
  src/main/java/com/sparta/devquiz/domain/quiz/repository/QuizUserRepositoryCustom.java
  src/main/java/com/sparta/devquiz/domain/quiz/repository/QuizUserRepositoryCustomImpl.java
  src/main/java/com/sparta/devquiz/domain/quiz/service/QuizService.java
Labels: refactor

#52 :sparkles: refactor(Quiz): 리팩토링 (#5)
  src/main/java/com/sparta/devquiz/domain/quiz/controller/QuizController.java
  src/main/java/com/sparta/devquiz/domain/quiz/dto/request/QuizAnswerSubmitRequest.java
  src/main/java/com/sparta/devquiz/domain/quiz/service/QuizService.java
Labels: refactor

#53 ✨ feat(Team): withdrawTeam 로직 변경
  src/main/generated/com/sparta/devquiz/domain/board/entity/QBoard.java
  src/main/generated/com/sparta/devquiz/domain/coin/entity/QCoin.java
  src/main/generated/com/sparta/devquiz/domain/comment/entity/QComment.java
  src/main/generated/com/sparta/devquiz/domain/comment/entity/QCommentLike.java
  src/main/generated/com/sparta/devquiz/domain/comment/entity/QCommentLikeId.java
  src/main/generated/com/sparta/devquiz/domain/quiz/entity/QQuiz.java
  src/main/generated/com/sparta/devquiz/domain/quiz/entity/QUserQuiz.java
  src/main/generated/com/sparta/devquiz/domain/team/entity/QTeam.java
  src/main/generated/com/sparta/devquiz/domain/team/entity/QTeamUser.java
  src/main/generated/com/sparta/devquiz/domain/team/entity/QTeamUserId.java
  src/main/generated/com/sparta/devquiz/domain/user/entity/QSkill.java
  src/main/generated/com/sparta/devquiz/domain/user/entity/QUser.java
  src/main/generated/com/sparta/devquiz/global/entity/QBaseTimeEntity.java
  src/main/java/com/sparta/devquiz/domain/team/response/TeamResponseCode.java
  src/main/java/com/sparta/devquiz/domain/team/service/TeamService.java
Labels: feat

#55 saveCoin 완성
  src/main/java/com/sparta/devquiz/domain/coin/controller/CoinController.java
  src/main/java/com/sparta/devquiz/domain/coin/dto/request/CoinSaveRequest.java
  src/main/java/com/sparta/devquiz/domain/coin/entity/Coin.java
  src/main/java/com/sparta/devquiz/domain/coin/enums/CoinContent.java
  src/main/java/com/sparta/devquiz/domain/coin/exception/CoinExceptionCode.java
  src/main/java/com/sparta/devquiz/domain/coin/service/CoinService.java
  src/main/java/com/sparta/devquiz/domain/quiz/service/QuizService.java
  src/test/java/com/sparta/devquiz/domain/coin/service/CoinServiceTest.java
Labels: refactor

#83 :sparkles: feat: getmygrass 작성 (#4)
  src/main/java/com/sparta/devquiz/domain/quiz/repository/QuizUserRepositoryCustom.java
  src/main/java/com/sparta/devquiz/domain/quiz/repository/QuizUserRepositoryCustomImpl.java
  src/main/java/com/sparta/devquiz/domain/quiz/service/QuizService.java
  src/main/java/com/sparta/devquiz/domain/user/controller/UserQueryController.java
  src/main/java/com/sparta/devquiz/domain/user/response/UserResponseCode.java
  src/main/java/com/sparta/devquiz/domain/user/service/query/UserQueryService.java
  src/main/java/com/sparta/devquiz/global/cors/WebMvcConfig.java
Labels: feat
